### PR TITLE
Fix the flakiness of testNFASerialization

### PR DESCRIPTION
**Pull request by NDR0216**
## What is the purpose of the change

* Running [org.apache.flink.cep.nfa.NFATest.testNFASerialization](https://github.com/NDR0216/flink/blob/b14411e7062c235cb28582a37e37decc7c425476/flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/nfa/NFATest.java#L205-L310) with [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool would discover flaky test.
* `NFATest.java` has been changed to solve the flakiness.

### Reproduce step
* Test Environment
  > Apache Maven: 3.6.3
  > Java: 11.0.20.1
  > OS: Ubuntu 20.04.6 LTS
  > Linux kernel: 5.4.0-164-generic

```Shell
mvn -pl flink-libraries/flink-cep edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.flink.cep.nfa.NFATest#testNFASerialization -DnondexMode=ONE
```

### Root cause
* `assertEquals()` at `NFATest.java` L308 would fail because the returned array elements of `PriorityQueue.toArray()` at `NFAState.java` L124-125 are in no particular order.
* [NonDex](https://github.com/TestingResearchIllinois/NonDex) would shuffle "the returned array" in the same permutation on the first invocation of an object.
* As a result, the returned array must be sorted to ensure that the comparison is correct.

https://github.com/NDR0216/flink/blob/b14411e7062c235cb28582a37e37decc7c425476/flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/nfa/NFATest.java#L308
https://github.com/NDR0216/flink/blob/b14411e7062c235cb28582a37e37decc7c425476/flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/nfa/NFAState.java#L115-L126

## Brief change log

* Sort the returned array of `PriorityQueue.toArray()` 
* Add the breakeven condition by using `hashCode()` because the original comparator [COMPUTATION_STATE_COMPARATOR](https://github.com/NDR0216/flink/blob/b14411e7062c235cb28582a37e37decc7c425476/flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/nfa/NFAState.java#L45-L55) only compares the timestamp and ID

## Verifying this change

This change is already covered by existing tests, such as org.apache.flink.cep.nfa.NFATest.testNFASerialization.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
    - No
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
    - No
  - The serializers: (yes / no / don't know)
    - No
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
    - No
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
    - No
  - The S3 file system connector: (yes / no / don't know)
    - No

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
    - No
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by kevin952** [comment]
Your fix looks good to me. Provided a brief description of the issue, cause and good fix!

**Comment by CaseyPan** [comment]
LGTM. It's good to have the testing environment stated, and the explanation for root cause is clear too!

**Comment by zzjas** [comment]
Please see email, thanks

**Comment by saurabh-shetty** [comment]
The fix looks good to me.

**Pull request closed without merging**
